[project]
name = "flut"
authors = ["sanmipaul"]
description = "A non-custodial, time-locked savings protocol on Stacks"
requirements = []
telemetry = true

[contracts.flut]
path = "contracts/flut.clar"
clarity_version = 2
epoch = "3.0"

[contracts.flut-nft]
path = "contracts/flut-nft.clar"
clarity_version = 2
epoch = "3.0"

[contracts.flut-goals]
path = "contracts/flut-goals.clar"
clarity_version = 2
epoch = "3.0"

[contracts.flut-streaks]
path = "contracts/flut-streaks.clar"
clarity_version = 2
epoch = "3.0"

[contracts.flut-split]
path = "contracts/flut-split.clar"
clarity_version = 2
epoch = "3.0"

[repl.analysis]
passes = ["check_checker"]

[[repl.analysis.check_checker]]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
